#test 1
name: Test_Release

# on:
#   push: 
on:
  push:

jobs:
  print_debug_info:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_TERRAFORM }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: release-${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false      

      # - name: Debug - Placeholder
      #   run: |
      #     echo "${{github.event.pull_request.merged}}"

      - name: Debug - Github Event Context Info
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"

      - name: Debug - Github Context Info
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Debug - Envs
        run: env